name: 'Egal Release Notify'
description: 'Sending a Telegram message about release.'
runs:
  using: 'composite'
  steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHANNEL_ID_FOR_RELEASE_NOTIFY }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          *bold \*text*
          _italic \*text_
          __underline__
          ~strikethrough~
          *bold _italic bold ~italic bold strikethrough~ __underline italic bold___ bold*
          [inline URL](http://www.example.com/)
          [inline mention of a user](tg://user?id=123456789)
          `inline fixed-width code`
          ```
          pre-formatted fixed-width code block
          ```
          ```python
          pre-formatted fixed-width code block written in the Python programming language
          ```
