name: 'Egal Release Notify'
description: 'Sending a Telegram message about release.'
inputs:
  release_json:
    description: 'Github Event Release as JSON'
    required: true
  telegram_channel_id:
    description: 'Telegram channel ID'
    required: true
  telegram_token:
    description: 'Telegram Token'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: docker://pandoc/latex:2.9
      with:
        args: --output=body.html ${{ steps.files_list.outputs.files }}
    - id: body-convertor
      shell: bash
      run: echo "::set-output name=html::$(cat body.html)"
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.telegram_channel_id }}
        token: ${{ inputs.telegram_token }}
        message: |
          New release: ${{ fromJson(inputs.release_json).name }}

          ${{ fromJson(inputs.release_json).body }}

          ${{ steps.body-convertor.outputs.html }}

#          *bold \*text*
#          _italic \*text_
#          __underline__
#          ~strikethrough~
#          *bold _italic bold ~italic bold strikethrough~ __underline italic bold___ bold*
#          [inline URL](http://www.example.com/)
#          [inline mention of a user](tg://user?id=123456789)
#          `inline fixed-width code`
#          ```
#          pre-formatted fixed-width code block
#          ```
#          ```python
#          pre-formatted fixed-width code block written in the Python programming language
#          ```
