name: 'Egal Release Notify'
description: 'Sending a Telegram message about release.'
inputs:
  release_json:
    description: 'Github Event Release as JSON'
    required: true
  telegram_channel_id:
    description: 'Telegram channel ID'
    required: true
  telegram_token:
    description: 'Telegram Token'
    required: true
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: echo ${{ fromJson(inputs.release_json).body }} > body.md
    - uses: docker://pandoc/latex:2.9
      with:
        args: --output=body.html body.md
    - id: body-convertor
      shell: bash
#      run: echo "::set-output name=html::$(sed -e 's/<[(p\/p)^>]*>//g' body.html)"
      run: echo "::set-output name=html::$(echo body.html)"
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.telegram_channel_id }}
        token: ${{ inputs.telegram_token }}
        format: html
        message: |
          New release: ${{ fromJson(inputs.release_json).name }}

          ${{ fromJson(inputs.release_json).body }}

          ${{ steps.body-convertor.outputs.html }}
