name: 'Egal Release Notify'
description: 'Sending a Telegram message about release.'
inputs:
  release_object:
    description: 'Github Event Release Object'
    required: true
  telegram_channel_id:
    description: 'Telegram channel ID'
    required: true
  telegram_token:
    description: 'Telegram Token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.telegram_channel_id }}
        token: ${{ inputs.telegram_token }}
        format: markdown
        message: |
          Name:
          ${{ inputs.release_object.name }}
          Body:
          ${{ inputs.release_object.body }}

#          *bold \*text*
#          _italic \*text_
#          __underline__
#          ~strikethrough~
#          *bold _italic bold ~italic bold strikethrough~ __underline italic bold___ bold*
#          [inline URL](http://www.example.com/)
#          [inline mention of a user](tg://user?id=123456789)
#          `inline fixed-width code`
#          ```
#          pre-formatted fixed-width code block
#          ```
#          ```python
#          pre-formatted fixed-width code block written in the Python programming language
#          ```
