name: 'Egal Release Notify'
description: 'Sending a Telegram message about release.'
inputs:
  repository_name:
    description: 'Repository name'
    required: true
  release_json:
    description: 'Github Event Release as JSON'
    required: true
  telegram_channel_id:
    description: 'Telegram channel ID'
    required: true
  telegram_token:
    description: 'Telegram Token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.telegram_channel_id }}
        token: ${{ inputs.telegram_token }}
        format: html
        message: |
          &#9898 <b>Release!</b>

          &#128194 <i>Product:</i> <b>${{ inputs.repository_name }}</b>
          &#128206 <i>Version:</i> <b>${{ fromJson(inputs.release_json).name }}</b>
          &#128466 <i>Discription:</i> <b><a href="${{ fromJson(inputs.release_json).html_url }}">link</a></b>
